version: '3'
services:
  db:
    image: mariadb:10.3.10-bionic
    container_name: ma0-tdi-mariadb
    networks:
      - backend
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: tdi
      MYSQL_USER: tdi
      MYSQL_PASSWORD: tdi
    ports:
      - 7001:3306

  web:
    hostname: tdi-php-apache.local
    build:
        context: .
        dockerfile: .docker/php/Dockerfile
    image: tdi_php_apache
    container_name: ma0-tdi-php_apache
    networks:
      - backend
      - frontend
    depends_on:
      - db
    volumes:
        - ./public_html/:/var/www/html
    ports:
      - 7000:80

networks:
  backend:
  frontend: