version: '3'
services:
  db:
    hostname: ma0-tdi-mariadb
    image: mariadb:10.3.10-bionic
    container_name: ma0-tdi-mariadb
    networks:
      - backend
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: tdi
      MYSQL_USER: tdi
      MYSQL_PASSWORD: tdi
    ports:
      - 7001:3306

  web:
    hostname: ma0-tdi-php-apache
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    image: ma0-tdi-php-apache:1.0
    container_name: ma0-tdi-php-apache
    networks:
      - backend
      - frontend
    depends_on:
      - db
    volumes:
        - ./php/:/var/www/html
    ports:
      - 7000:80

networks:
  backend:
  frontend:
